#!/bin/bash

find_dirs() {
	echo $(emacsclient -e "(proj--get-paths)" | sed -ze 's/(\(.*\))/\1/') | xargs -n1
}

emacs_attached() {
    [ "$(emacsclient -e '(- (length (frame-list)) 1)')" = 0 ] && return 1 || return 0
}

switch_to() {
    if emacs_attached; then
        emacsclient -e "(proj-set-dir \"$1\")"
    else
        emacsclient -ce "(proj-set-dir \"$1\")"
    fi
}

# get selected
selected=$(find_dirs | swenu -coil 15)
[ -z "$selected" ] && exit 1;
selected="${selected/\~/$HOME}"

# set emacs project
switch_to "$selected"

# focus emacs
swaymsg [con_id="$(swaymsg -t get_tree | jq -r '.nodes[1].nodes[].nodes[] | .. | (.id|tostring) + " " + .app_id?' | grep emacs | awk '{print $1}')"] focus
